apiVersion: v1
kind: Service
metadata:
  name: {{ include "chatapplication.fullname" . }}-backend
  labels:
    {{- include "chatapplication.labels" . | nindent 4 }}

spec:
  type: {{ .Values.backend.service.type }}

  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
      protocol: TCP

  selector:
    {{- include "chatapplication.selectorLabels" . | nindent 4 }}