# =======================
# Backend Configuration
# =======================
backend:
  replicaCount: 1

  image:
    repository: kartikmehta/backend
    tag: latest
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 5000

  resources:
    limits:
      cpu: "500m"
      memory: "256Mi"

  labels:
    app: backend
  selectorLabels:
    app: backend

# =======================
# Frontend Configuration
# =======================
frontend:
  replicaCount: 1

  image:
    repository: kartikmehta/frontend
    tag: latest
    pullPolicy: IfNotPresent

  service:
    type: NodePort
    port: 80
    nodePort: 30007   # ✅ added

  resources:
    limits:
      cpu: "500m"
      memory: "256Mi"

  labels:
    app: frontend
  selectorLabels:
    app: frontend

# =======================
# MongoDB Configuration
# =======================
mongodb:
  replicaCount: 1

  image:
    repository: mongo
    tag: "6.0"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 27017

  resources:
    limits:
      cpu: "500m"
      memory: "256Mi"

  persistence:
    enabled: true
    size: 1Gi
    accessMode: ReadWriteOnce
    storageClass: standard   # better than ""

  labels:
    app: mongodb


# =======================
# Service Account
# =======================
serviceAccount:
  create: true
  name: ""
  automount: true
  annotations: {}


# =======================
# Ingress (Optional)
# =======================
ingress:
  enabled: false

  className: ""
  annotations: {}

  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix

  tls: []