apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongo
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chatapplication.labels" . | nindent 4 }}

spec:
  clusterIP: None   # 🔥 Headless service (VERY IMPORTANT)

  ports:
    - port: {{ .Values.mongodb.service.port }}
      targetPort: {{ .Values.mongodb.service.port }}
      protocol: TCP

  selector:
    {{- include "chatapplication.selectorLabels" . | nindent 4 }}