apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongo
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chatapplication.dblabels" . | nindent 4 }}

spec:
  clusterIP: None   # 🔥 Headless service (VERY IMPORTANT)

  ports:
    - port: {{ .Values.db.service.port }}
      targetPort: {{ .Values.db.service.port }}
      protocol: TCP

  selector:
    {{- include "chatapplication.dbselectorLabels" . | nindent 4 }}