apiVersion: v1
kind: Service
metadata:
  name: {{ include "chatapplication.frontendfullname" . }}
  labels:
    {{- include "chatapplication.frontendlabels" . | nindent 4 }}

spec:
  type: {{ .Values.frontend.service.type }}

  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http

  selector:
    {{- include "chatapplication.frontendselectorLabels" . | nindent 4 }}