apiVersion: v1
kind: Service
metadata:
  name: {{ include "chatapplication.fullname" . }}-frontend
  labels:
    {{- include "chatapplication.labels" . | nindent 4 }}

spec:
  type: {{ .Values.frontend.service.type }}

  ports:
    - name: http-frontend
      protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.nodePort }}

  selector:
    {{- include "chatapplication.selectorLabels" . | nindent 4 }}