apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
      app: {{.Values.frontend.labels.app}}

spec:
  type: {{ .Values.frontend.service.type }}

  ports:
    - name: http-frontend
      protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.nodePort }}

  selector:
    app: frontend